version: '3'

services:

  api:
    container_name: thousandsunny-api 
    build:
        context: .
        dockerfile: ./docker/thousandsunny-api/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/var/src/thousandsunny-api
    networks:
      - bubble
    tty: true

networks:
  bubble:
    external: true